package main

var LOG_LEVEL = 6

var LOOPING = true
var LOOP_SPEED = 35
var SENSOR_INIT_DELAY = 200
var START_LOOP_DELAY = 300
var END_DELAY = 200

var NONE = "none"
var BLACK = "black"
var WHITE = "white"
var SILVER = "silver"
var GREEN = "green"

var LEFT = 0
var RIGHT = 1
var BOTH = 2

var BEHAVIOUR = "none"
var DO_GREEN_TURN = true
var DO_WATER_TOWER = false
var DO_CHEMICAL_SPILL = true

var WATER_TOWER_DETECT_DISTANCE = 900
var WATER_TOWER_DETECT_COUNT = 4
var WATER_TOWER_VERIFY_DISTANCE = WATER_TOWER_DETECT_DISTANCE + 10
var WATER_TOWER_VERIFY_COUNT = 5
var WATER_TOWER_VERIFY_ATTEMPTS = 150
var WATER_TOWER_VERIFY_SPEED = 40
var WATER_TOWER_TURN_ANGLE = 1100
var WATER_TOWER_TURN_SPEED = 100
var WATER_TOWER_RECAPTURE_ANGLE = 30

var GREEN_DETECT_RGB_DIFFERENCE = 6
var GREEN_FINISH_ANGLE = 700